//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainCoreDiplom.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int ID_Log { get; set; }
        public Nullable<int> ID_User { get; set; }
        public string Action { get; set; }
        public string TableName { get; set; }
        public Nullable<int> RecordID { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
