//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainCoreDiplom.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceSettings
    {
        public int ID_Setting { get; set; }
        public Nullable<int> ID_TypeWagon { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public string Season { get; set; }
        public Nullable<decimal> Coefficient { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Type_Wagons Type_Wagons { get; set; }
    }
}
