//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainCoreDiplom.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Returns
    {
        public int ID_Return { get; set; }
        public Nullable<int> ID_Ticket { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public string Reason { get; set; }
        public Nullable<int> ProcessedBy { get; set; }
    
        public virtual Tickets Tickets { get; set; }
        public virtual Users Users { get; set; }
    }
}
