//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainCoreDiplom.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.Returns = new HashSet<Returns>();
        }
    
        public int ID_Ticket { get; set; }
        public int ID_Passanger { get; set; }
        public int ID_Seat { get; set; }
        public int ID_Schedule { get; set; }
        public Nullable<System.DateTime> Date_buy { get; set; }
        public decimal Stoimost { get; set; }
        public string Status { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual Passangers Passangers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Returns> Returns { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Seats Seats { get; set; }
    }
}
