//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainCoreDiplom.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPreferences
    {
        public int ID_Preference { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<bool> PreferWindow { get; set; }
        public Nullable<bool> PreferAisle { get; set; }
        public Nullable<bool> PreferLower { get; set; }
        public Nullable<bool> PreferNearToilet { get; set; }
        public Nullable<bool> PreferPowerOutlet { get; set; }
        public Nullable<bool> PreferQuiet { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
